<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */ 
 
class Manage_laporan extends CI_Controller{
    function __construct()
    {
         parent::__construct();
        $this->load->model('model_laporan');
        

    } 

    /*
     * Listing of pemesanan
     */
   function index()
    { 
        $table = 'monitoring';
        $this->load->model('model_laporan','monitoring');

        $data['kodeKompos'] = $this->model_laporan->getKodekompos();
        
        $data['_view'] = 'pemilik/laporan/index';
        $this->load->view('layout',$data);
   
    }
    function search_keyword($waktu)
    {
    
        $data['results'] = $this->model_laporan->search($waktu);
        $data['results2'] = $this->model_laporan->search2($waktu);

        $data['_view'] = 'pemilik/laporan/flaporan';
       
        $this->load->view('layout',$data);
          
    }
  

}
