<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */ 
 
class Manage_pegawai extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('model_pegawai');
    } 

    /*
     * Listing of pemesanan
     */
    function index()
    {
		
		$this->load->model('model_pegawai','pegawai');
		$data['pegawai'] = $this->model_pegawai->get_all_pegawai();
        
        $data['_view'] = 'pemilik/pegawai/index';
        $this->load->view('layout',$data);
    }

    /*
     * Adding a new pemesanan
     */
    function add()
    {   
        $this->load->model('model_pegawai');
        $data = array(
            'nama_depan' => $this->input->post('nama_depan'),
            'nama_belakang' => $this->input->post('nama_belakang'),
            'nmr_hp' => $this->input->post('nmr_hp'),
            'username' => $this->input->post('username'),
            'password' => $this->input->post('password'),
         );
         $data = $this->model_pegawai->add('pegawai', $data);
        
         redirect('manage_pegawai/index');
        
    }  

    /*
     * Editing a pemesanan
     */


    function edit($id_user)
    {   
        // check if the pemesanan exists before trying to edit it
        $data['pegawai'] = $this->model_pegawai->get_pegawai($id_user);
        
        if(isset($data['pegawai']['id_user']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'nama_depan' => $this->input->post('nama_depan'),
                    'nama_belakang' => $this->input->post('nama_belakang'),
                    'nmr_hp' => $this->input->post('nmr_hp'),
                    'username' => $this->input->post('username'),
                    'password' => $this->input->post('password'),
                );

                $this->model_pegawai->edit($id_user,$params);            
                redirect('manage_pegawai/index');
            }else{
                $this->load->model('model_pegawai');
                $data['all_pegawai'] = $this->model_pegawai->get_all_pegawai();

                $data['_view'] = 'pemilik/pegawai/edit';
                $this->load->view('layout',$data);
            }
        }
        else
            show_error('The pegawai you are trying to edit does not exist.');
    } 

    /*
     * Deleting pemesanan
     */
    function delete($id_user)
    {
        $pegawai = $this->model_pegawai->get_pegawai($id_user);

        // check if the pemesanan exists before trying to delete it
        if(isset($pegawai['id_user']))
        {
            $this->model_pegawai->delete($id_user);
            redirect('manage_pegawai/index');
        }
        else
            show_error('The pemesanan you are trying to delete does not exist.');
    }
    
}
