<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Model_pegawai extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pemesanan by id_pemesanan
     */
    function get_pegawai($id_user)
    {
        return $this->db->get_where('pegawai',array('id_user'=>$id_user))->row_array();
    }
        
    /*
     * Get all pemesanan
     */
    function get_all_pegawai()
    {
        $this->db->order_by('id_user', 'asc');
        $this->db->select('*');
        $this->db->from("pegawai");
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new pemesanan
     */
    function add($table,$data){
 // Kode ini digunakan untuk memasukan record baru kedalam sebuah tabel
        return $this->db->insert($table, $data); // Kode ini digunakan untuk mengembalikan hasil $res
    }
    
    /*
     * function to update pemesanan
     */
    function edit($id_user,$params)
    {
        $this->db->where('id_user',$id_user);
        return $this->db->update('pegawai',$params);
    }
    
    function delete($id_user)
   {
        $this->db->delete('pegawai',array('id_user' => $id_user));
        return $this->db->delete('pegawai',array('id_user'=>$id_user));
    }

}